name: Gitleaks PR Secret Scan

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gitleaks:
    uses: clouddrove/github-shared-workflows/.github/workflows/gitleaks-pr-scan.yml@a9fc2fae0eceafcdd4a812c23a3febd9c416428b # pinned to latest
    secrets: inherit
