name: Tag Release

on:
  pull_request:
    types: [closed]

jobs:
  release:
    uses: clouddrove/github-shared-workflows/.github/workflows/tag-release.yml@9db6ce0e27e44d60dfb166a04f7ecddde842ec4f # pinned to latest
    with:
      target_branch: master
    secrets:
      GITHUB: ${{ secrets.GITHUB_TOKEN }}
